source 'https://rubygems.org'

# Test driver
gem 'capybara', '>= 3.32.2'

# Webdriver for chrome headless
gem 'selenium-webdriver'

# Use nice acceptance tests DSL
gem 'rspec'

# Run tests nicely
gem 'rake'
